LOCAL_SETTINGS = True 

from settings import * 
import socket 
import media_processor 

ADMINS = (
    ('Your Name', 'your_email@example.com'),
)

DEBUG = True
# Set DEBUG = True if on the dev server
if socket.gethostname() == 'madman.notyourwork.com':
    DEBUG = False
else:
    DEBUG = True

TEMPLATE_DEBUG = DEBUG

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': '',                      
        'USER': '',         
        'PASSWORD': '',           
        'HOST': '', 
        'PORT': '',             
    }
}

SECRET_KEY = ''

TIME_ZONE = 'America/New_York'

#This is where stuff goes that will be generated by madman, should be empty and outside django
MEDIA_ROOT = ''
MEDIA_URL = ''

#This is where the css/js/etc goes...it should be outside the django, copy contents from the repo or symlink
STATIC_ROOT = '' 
STATIC_URL = ''

#Where is your django admin media assets available
ADMIN_MEDIA_PREFIX = ''

STATICFILES_DIRS = (
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler'
        }
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'INFO',
            'propagate': True,
        },
    }
}

#where media is downloaded to 
MADMAN_DOWNLOAD_PLACES = [
    #'/media/downloads/ircdownloads/complete/',
    '/media/downloads/seeding/',
]

#where media is seeded from 
MADMAN_SEEDING_PLACES = [    
    '/media/downloads/seeding', 
]

#where your media definition goes 
#1. define eachmedia type as dict keys 
#2. define values for each key as a tuple
#   each tuple contains a processor function, 
#   and tuples of paths to media along with a regex
#   to match items for this particular path 
MADMAN_MEDIA_CONFIG  = {
    'media_type_1' : (
        media_processor.media_processor, 
        ('/path/to/media_type_1/1/', "[0-9A-M]"), 
        ('/path/to/media_type_1/2/', '[N-Z]'), 
    ),
}
